services:
  iam:
    build:
      context: .
      target: production
    depends_on:
      - iam-db
    env_file:
      - .env
    networks:
      - iam-network
    restart: unless-stopped

  iam-db:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - iam-db-data:/var/lib/postgresql/data
    networks:
      - iam-network
    restart: unless-stopped

networks:
  iam-network:
    driver: bridge

volumes:
  iam-db-data:
